implemented routes, protected routes, and redirect to login page if no JWT token in localstorage
pradip-varicon/Dashboard-Practice pull request #3
Opened 2024-08-22 10:16 UTC by pradip-varicon

2024-08-22 10:55 UTC, sudipsth08 reviewed
- Make title short and add the relevant info in description
- Repo name should be in small case `dashboard-practice`

2024-08-22 11:01 UTC, sudipsth08 requested changes

2024-08-22 11:01 UTC, sudip-sth commented on src/context/AuthContext.tsx
> +      const authToken = localStorage.getItem("authToken");
make the const for localStorage keys as it must be accessed across multiple components

2024-08-22 11:01 UTC, sudip-sth commented on src/context/AuthContext.tsx
> +  const login = async (username: string, password: string) => {
Its not necessary to put api calls in context

2024-08-22 11:01 UTC, sudip-sth commented on src/pages/LoginPage.tsx
> +    } catch {
add success message on successful login like toast

2024-08-22 11:01 UTC, sudip-sth commented on src/pages/LoginPage.tsx
> +          variant="outlined"
Always add name and type props for formfields

2024-08-22 11:01 UTC, sudipsth08 commented on src/services/authService.ts
> +const API_URL = "https://dummyjson.com/auth";
put this variable in constants+

2024-08-23 02:44 UTC, pradip-varicon reviewed
implemented the const variables for localStorage keys as it must be accessed across multiple components.

2024-08-23 03:25 UTC, pradip-varicon commented
separated API calls from context file, implemented environment variable, and used const variables across service file for localstorage

2024-08-23 03:32 UTC, pradip-varicon commented
added necessary props in the input fields (ie. name, type)

2024-08-23 03:43 UTC, pradip-varicon commented
implemented react-toastify for success or failure toast notifications

2024-08-23 03:49 UTC, sudipsth08 requested changes

2024-08-23 03:49 UTC, sudipsth08 commented on src/services/authService.ts
> +const API_URL = import.meta.env.VITE_SERVER_BASE_URL;
keep this in constant

2024-08-23 04:00 UTC, pradip-varicon commented
**login credentials:**

username: emilys
password: emilyspass

2024-08-23 04:26 UTC, merged