Accounting code/react table
pradip-varicon/Dashboard-Practice pull request #7
Opened 2024-08-30 13:21 UTC by pradip-varicon

added react table, contexts , types, services etc. in accounting code section to fetch accounting codes and render using mui react table v2.

![image](https://github.com/user-attachments/assets/48558f8c-136d-448b-aa6a-ee056e3434cb)

2024-08-30 15:10 UTC, sudipsth08 requested changes

2024-08-30 15:10 UTC, sudipsth08 commented on src/components/LoadingSpinner.tsx
> +        height: "60vh",
Put syyles on seperate style.tsx file

2024-08-30 15:10 UTC, sudipsth08 commented on src/context/AccountingContext.tsx
> +    const fetchData = async () => {
Dont fetch api in context and use react query

2024-08-30 15:11 UTC, sudipsth08 commented
please use other names. Lets not use the exact names we have in our main app like acc codes.

2024-09-02 09:43 UTC, pradip-varicon commented
theme and all the nav item names that matches Varicon main app has changed.

![image](https://github.com/user-attachments/assets/3dbbb44a-cb20-41ab-ae09-f82b1d8f3bd8)

2024-09-04 05:11 UTC, merged